# build stage
FROM node:12.4.0-alpine as builder

WORKDIR /app

COPY package.json package-lock.json ./

COPY . /app

COPY .env /app/.env

RUN npm run build

# production stage
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]